import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { inr, plural, STATUS_TONE, titleise, when } from "../lib/format";

const STAGE_COLOR = {
  act: "var(--brand)",
  comply: "var(--warning)",
  stop: "var(--danger)",
  observe: "var(--good)",
  violation: "var(--danger)",
  diagnose: "var(--good)",
  detect: "var(--muted)",
};

const HIDDEN_FACTORS = new Set(["timing_note", "note", "model"]);

function AuditStep({ entry }) {
  const detail = entry.detail ?? {};
  const model = detail.outcome_model;

  return (
    <div className="step" data-stage={entry.stage}>
      <div className="step-top">
        <span className="stage" style={{ color: STAGE_COLOR[entry.stage] ?? "var(--muted)" }}>
          {entry.stage}
        </span>
        <span className="when">{when(entry.at)}</span>
        <span className="when" style={{ opacity: 0.6 }}>
          #{entry.seq} · {entry.entry_hash}
        </span>
      </div>

      <div className="body">{entry.decision}</div>

      {detail.message && (
        <div className="msg">
          {detail.message}
          <div style={{ color: "var(--muted)", fontSize: 11, marginTop: 6 }}>
            {detail.message_source === "llm"
              ? "generated by Claude, validated before send"
              : "deterministic template"}
            {detail.payment_link && (
              <> · <a href={detail.payment_link} target="_blank" rel="noopener noreferrer">
                live Razorpay link
              </a></>
            )}
          </div>
        </div>
      )}

      {model && (
        <div className="factors">
          {Object.entries(model)
            .filter(([k]) => !HIDDEN_FACTORS.has(k))
            .map(([k, v]) => (
              <span key={k}>{titleise(k)}: <b>{String(v)}</b></span>
            ))}
          {model.timing_note && (
            <span style={{ gridColumn: "1 / -1", color: "var(--muted)", marginTop: 3 }}>
              timing: {model.timing_note}
            </span>
          )}
        </div>
      )}
    </div>
  );
}

export default function CaseDrawer({ eventId, onClose }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    let live = true;
    setData(null);
    setError(null);
    api.trail(eventId)
      .then((d) => live && setData(d))
      .catch((e) => live && setError(e.message));
    return () => { live = false; };
  }, [eventId]);

  useEffect(() => {
    const onKey = (e) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div className="scrim" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="sheet" role="dialog" aria-modal="true" aria-label="Case decision trail">
        {!data && !error && <div className="empty"><span className="spinner" />Loading trail…</div>}
        {error && <div className="empty">Could not load this case: {error}</div>}

        {data && (() => {
          const { event: e, diagnosis: dx, playbook: pb, counterpart: cp } = data;
          return (
            <>
              <div className="sheet-top">
                <div>
                  <h3>{e.customer_name || e.customer_id} — {inr(e.amount)}</h3>
                  <div style={{ color: "var(--muted)", fontSize: 12.5 }}>
                    {titleise(e.event_type)} · {e.external_ref} · {e.segment} ·
                    policy {e.policy_version}
                  </div>
                  <div className="controls" style={{ marginTop: 9 }}>
                    <span className={`badge ${STATUS_TONE[e.status] ?? "b-muted"}`}>{e.status}</span>
                    {dx.hard_stop && <span className="badge b-danger">hard stop</span>}
                    {dx.needs_new_instrument && (
                      <span className="badge b-warning">instrument unusable</span>
                    )}
                    {e.consent.dnc && <span className="badge b-danger">do not contact</span>}
                    <span className="badge b-muted">
                      {plural(e.attempts, "attempt")} · {plural(e.contacts, "message")} ·
                      ₹{e.cost.toFixed(2)} spent
                    </span>
                  </div>
                </div>
                <button type="button" className="icon-btn" onClick={onClose} aria-label="Close">✕</button>
              </div>

              <div className="grid g-2">
                <div className="panel">
                  <h2>Diagnosis</h2>
                  <dl className="kv">
                    <dt>Raw signal</dt>
                    <dd>
                      <code>{e.signal.reason || "none"}</code>{" "}
                      {e.signal.code && <code>{e.signal.code}</code>}
                    </dd>
                    <dt>Description</dt><dd>{e.signal.description || "—"}</dd>
                    <dt>Root cause</dt>
                    <dd><b style={{ color: "var(--text)" }}>{dx.label}</b></dd>
                    <dt>Method</dt>
                    <dd>
                      {dx.source}
                      {dx.confidence != null && ` · ${(dx.confidence * 100).toFixed(0)}% confidence`}
                    </dd>
                    <dt>Reasoning</dt><dd>{dx.rationale || "—"}</dd>
                  </dl>
                  <div style={{
                    marginTop: 12, padding: "10px 12px", background: "var(--surface-2)",
                    borderRadius: 8, fontSize: 12.5, color: "var(--text-2)",
                    borderLeft: "3px solid var(--brand)",
                  }}>
                    <b style={{ color: "var(--brand-deep)" }}>Why this constrains the options:</b>{" "}
                    {dx.physics}
                  </div>
                </div>

                <div className="panel">
                  <h2>Playbook — {pb.max_contacts} contact budget</h2>
                  <div style={{ color: "var(--muted)", fontSize: 12, marginBottom: 11 }}>
                    {pb.rationale}
                  </div>
                  <div className="ladder">
                    {pb.steps.map((s) => (
                      <div className={`rung ${s.state}`} key={s.n}>
                        <span className="n">{s.n}</span>
                        <span>
                          <b>{titleise(s.action)}</b> via {s.channel}
                          {s.note && <span className="note">{s.note}</span>}
                        </span>
                        <span style={{ color: "var(--muted)", fontSize: 11.5, whiteSpace: "nowrap" }}>
                          +{s.delay}{s.timing ? ` · ${titleise(s.timing)}` : ""}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {cp && (
                <div className="panel" style={{ marginBottom: 15 }}>
                  <h2>The same customer under the baseline policy</h2>
                  <div className="controls">
                    <span className={`badge ${STATUS_TONE[cp.status] ?? "b-muted"}`}>{cp.status}</span>
                    <span style={{ fontSize: 12.5, color: "var(--text-2)" }}>
                      {plural(cp.attempts, "attempt")} · {plural(cp.contacts, "message")} · recovered{" "}
                      <b style={{ color: cp.amount_recovered > 0 ? "var(--good)" : "var(--muted)" }}>
                        {cp.amount_recovered > 0 ? inr(cp.amount_recovered) : "nothing"}
                      </b>
                    </span>
                  </div>
                  <div style={{ marginTop: 10, fontSize: 12.5, color: "var(--muted)" }}>
                    {cp.actions.length
                      ? cp.actions.map((a, i) => (
                          <span key={i}>
                            {i > 0 && " → "}
                            {titleise(a.action_type)} ({a.channel})
                            {a.success_probability != null &&
                              ` — ${(a.success_probability * 100).toFixed(1)}% chance`}
                          </span>
                        ))
                      : "no actions taken"}
                  </div>
                </div>
              )}

              <div className="panel">
                <h2>Decision trail — every step, with its reasoning</h2>
                <div className="trail">
                  {data.audit_trail.map((t) => <AuditStep key={t.seq} entry={t} />)}
                </div>
              </div>
            </>
          );
        })()}
      </div>
    </div>
  );
}
