"""Engine / session wiring, kept separate from the table definitions."""
from sqlalchemy import create_engine, event
from sqlalchemy.orm import sessionmaker, declarative_base

from app.config import DATABASE_URL

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {},
)

if DATABASE_URL.startswith("sqlite"):
    @event.listens_for(engine, "connect")
    def _sqlite_pragmas(dbapi_connection, _record):
        """
        A batch writes thousands of small rows — audit entries, actions, state
        transitions — each inside its own transaction. On SQLite's default
        settings every one of those is a separate fsync, which dominated the
        runtime of a batch (16s for 60 cases) with no durability benefit that
        matters here: the database is regenerated by `/batch/run`.

        WAL plus synchronous=NORMAL keeps crash-safety against process death
        (which is what we actually care about) while dropping the per-commit
        fsync. Foreign keys are enforced rather than silently ignored.
        """
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.execute("PRAGMA synchronous=NORMAL")
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
